language: node_js
node_js:
- '10'
sudo: enabled
before_install:
- echo "---------- start to install dependencies ----------"
- openssl aes-256-cbc -K $encrypted_904589bea512_key -iv $encrypted_904589bea512_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
install: npm install
before_script: echo "---------- start to build ----------"
script:
- npm run build
after_success:
  - rsync -avr -e 'ssh -p 22' --delete-after dist/* root@182.254.232.213:/usr/www/onefire
addons:
  ssh_known_hosts: 182.254.232.213