language: node_js
node_js: '10'
cache:
  yarn: true
addons:
  ssh_known_hosts: 182.254.232.213
before_install:
  - openssl aes-256-cbc -K $encrypted_904589bea512_key -iv $encrypted_904589bea512_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa
script:
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: 
    - rsync -avr --delete-after $TRAVIS_BUILD_DIR/dist/* root@182.254.232.213:/usr/www/onefire
  on:
    branch: master
