language: node_js
node_js:
  - "10"
sudo: enabled
before_install: echo "---------- start to install dependencies ----------"
install: npm install
before_script: echo "---------- start to build ----------"
script:
  - npm run build
